### PR TITLE
Fix for Keras 2.1 : num_class is now num_classes for DirectoryIterator

### PR DESCRIPTION
**Pull request by AMairesse**

### CODE REVIEW

**Comment by roebius** [comment]
Hello Antoine,
thank you for sending the PR. I think I will be able to merge it by the end of this week and update the README, as I am re-testing all the notebooks with Keras 2.1 and the latest versions of the backend engines.

**Comment by AMairesse** [comment]
Hi,
Forgot to mention that there is a fix currently waiting in Keras and it will also be needed in order to be able to use Keras 2.1 and Theano 1.0
https://github.com/fchollet/keras/commit/e0d9fcb91ad4cd8d993c3225cda508a30b3095b9
Currently this fix is needed in order to be able to use the first lesson with the last versions of Theano and Keras.
I've not looked into the others notebooks for now :-)

**Comment by roebius** [comment]
Thanks for letting me know. In this case I think it makes sense for me to postpone the review activity until after the Keras fix is released.

**Comment by AMairesse** [comment]
I agree

**Comment by pisymbol** [comment]
I believe it has been released now.

**Comment by roebius** [comment]
I plan to release a revision of the notebooks for Keras 2.1 in January. Thanks for your interest.

**Comment by roebius** [comment]
Merging now before updating a few additional modules. Thank you!

**Pull request merged**
